DROP TABLE IF EXISTS "user";
DROP TABLE IF EXISTS "list";

CREATE TABLE "user"(
	id INTEGER PRIMARY KEY IDENTITY,
	username TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL
);

CREATE TABLE  "list"(
	id INTEGER PRIMARY KEY IDENTITY,
	author_id INTEGER NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (author_id) REFERENCES "user"(id)
);

